# xen-build-template.conf

# Set to "true" to build from a local folder on your PC
_use_local_code="false"
# The absolute path to your local Xen Git repository
_local_source_path="/home/user/code/xen"

if [[ "${_use_local_code}" == "true" ]]; then
    # When building locally, makepkg will clone from this folder
    _xen_version=""
    _xen_branch="HEAD"
    _xen_repo="git+file://${_local_source_path}"
else
    # Upstream source downloading
    _xen_version="4.22.0"
    _xen_branch="stable-4.22"
    _xen_repo="git+https://xenbits.xen.org/git-http/xen.git"
fi

# Set to true if you need stub domains
_build_stubdom=
# Set to true to compile with debug symbols
_build_debug=

# Appended to the package name and EFI binary (e.g., xen-testbuild.efi)
_build_suffix=
# Set to "true" to delete userspace tools and prevent conflicts with your main Xen install
_hypervisor_only=

# Add your custom patch file names here. They must be in the same directory as this PKGBUILD.
_custom_patches=(
    # "experimental-feature.patch"
)

_boot_dir="/boot"
_efi_dir="/boot/EFI"
_efi_mountpoint="/boot/EFI"
