# xen-build.conf

_use_local_code="false"
_local_source_path="/home/user/code/xen"

if [[ "${_use_local_code}" == "true" ]]; then
    _xen_version="build.custom"
    _xen_branch="HEAD"
    _xen_repo="git+file://${_local_source_path}"
else
    _xen_version="4.22.0"
    _xen_branch="stable-4.22"
    _xen_repo="git+https://xenbits.xen.org/git-http/xen.git"
fi

_build_stubdom="false"
_build_debug="false"

_build_suffix="-base"
_hypervisor_only="false"

_custom_patches=(
)

_boot_dir="/boot"
